services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - strava_db:/app/data
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-include "*.html" --reload-include "*.css"

volumes:
  strava_db: